var products = [
['Żurawina susz.',1,'','Przekąski'],
['Zupa błyskaw.',1,'','Przekąski'],
['Ziemniaki 5kg, św',1,'','Warzywa'],
['Wrigleys Guma II',0,'','Słodycze'],
['Worki na śmieci 69L',0,'','Prod. przemysłowe'],
['Wkładki hig.long',0,'','Prod. przemysłowe'],
['Wino Cardal',2,'btn-success','Napoje'],
['Wafle ryżowe',0,'','Słodycze'],
['Tymb.Nekt.eop29%',0,'','Napoje'],
['Twaróg półtł. klin.',1,'','Nabiał'],
['Szynka Szwar.kroj.',0,'','Wędliny'],
['Szynka got.delik.',0,'','Wędliny'],
['Szczypiorek św.',0,'','Warzywa'],
['Sokołów Kabanosy',0,'','Wędliny'],
['Skrzydła z kurczaka',0,'','Mięso'],
['Serek wiej.bez lak.',0,'','Nabiał'],
['Ser w plastrach',0,'','Nabiał'],
['Ser topiony pl.200g',0,'','Nabiał'],
['Ser Mozzarella',0,'','Nabiał'],
['Ser Gouda',1,'btn-success','Nabiał'],
['Schab wieprzowy b/k',0,'','Mięso'],
['Ryż Basmati',0,'','Art. mączne'],
['Pure Frankfurterki',0,'','Wędliny'],
['Ptasie mleczko',1,'','Słodycze'],
['Pstrąg łososiowy wędzony',0,'','Przekąski'],
['Przyprawa Majeranek',1,'','Przyprawy'],
['Popcorn do mik.solony',0,'','Przekąski'],
['Pomidory w puszce',0,'','Słoiki/puszki'],
['Pomidor kiśc świeży',1,'btn-success','Warzywa'],
['Płatki kosmetyczne',0,'','Prod. przemysłowe'],
['Płatki Corn Flakes',0,'','Przekąski'],
['Pizza Margherit399g',1,'btn-success','Mrożonki'],
['Piwo Perlenb. 0,5L',4,'btn-success','Napoje'],
['Pierogi z kap./grzyb',1,'btn-success','Mrożonki'],
['Pieczarki świeże',0,'','Warzywa'],
['Patyczki kosmetyczne',0,'','Prod. przemysłowe'],
['Parówki Berlinki',0,'','Wędliny'],
['Papryka c. świeża',0,'','Warzywa'],
['Papr żółta św. luz',0,'','Warzywa'],
['Paluszki słone',1,'btn-success','Przekąski'],
['Paluszki serowe',0,'','Nabiał'],
['Orzechy nerkow.XXL',0,'','Przekąski'],
['Ogórki ziel świeże',1,'btn-success','Warzywa'],
['Oetker Budyń',0,'','Przyprawy'],
['Nutella kr.cz.359g',0,'','Słoiki/puszki'],
['Nekt.pomar.59%1,5L',0,'','Napoje'],
['Nat.pietruszki św.',1,'btn-success','Warzywa'],
['Mleko bez laktozy',0,'','Nabiał'],
['Mleczko wan.w czekol',0,'','Słodycze'],
['Migdały łuskane',0,'','Przyprawy'],
['Mięso mielone woł.Pr',0,'','Mięso'],
['Mięso miel.w.—woł.',0,'','Mięso'],
['Mieszanka sałat',0,'','Warzywa'],
['Miesz. żur. i nerk.',0,'','Przekąski'],
['Miesz chińska mroż.',0,'','Mrożonki'],
['Mąka tortowa459 1kg',0,'','Art. mączne'],
['Masz.d.gol. Venus',0,'','Prod. przemysłowe'],
['Maseczki 2x6ml',0,'','Prod. przemysłowe'],
['Makaron kokard.500g',0,'','Art. mączne'],
['Łosoś wędzony199g 2',0,'','Przekąski'],
['Łosoś dziki 9,378',0,'','Przekąski'],
['Lody Twister',0,'','Słodycze'],
['Lody Sandwich',6,'btn-success','Słodycze'],
['Lody jogurt. 469ml',0,'','Słodycze'],
['Liście laurowe',0,'','Przyprawy'],
['Lipton Ice Tea',0,'','Napoje'],
['Lipton Herb.mroż.',0,'','Napoje'],
['Piwo Lech Free Lim.Mięta',1,'','Napoje'],
['Kukurydza konserw.',0,'','Słoiki/puszki'],
['Koreczki śledziowe',0,'','Przekąski'],
['Kopytka',0,'','Mrożonki'],
['Koperek św.',0,'','Warzywa'],
['Koncentrat pom.',0,'','Słoiki/puszki'],
['Kinder Bueno baton',0,'','Słodycze'],
['Kiełki sort.',1,'btn-success','Warzywa'],
['Kiełb. krak. sucha',0,'','Wędliny'],
['Ketchup łagodny',0,'','Słoiki/puszki'],
['Kania Majonez',0,'','Słoiki/puszki'],
['Kabanosy drob.Tar.',0,'','Wędliny'],
['Jog.nat.3% b.lakt.',3,'btn-success','Nabiał'],
['Jaja L',0,'','Nabiał'],
['Herbatniki Maltanki',0,'','Słodycze'],
['Herbata ziel.79g',0,'','Napoje'],
['herb.Rooibos,Pu—erh',0,'','Napoje'],
['Groszek kons.puszka',0,'','Słoiki/puszki'],
['Granola M.Czek.—kok.',0,'','Słodycze'],
['Frytki mrożone 7x7',1,'btn-success','Mrożonki'],
['Folia spożywcza',0,'','Prod. przemysłowe'],
['Favita Ser',0,'','Nabiał'],
['Fasola zielona świeża',0,'','Warzywa'],
['Donut Milka św',3,'','Słodycze'],
['D.Szynka got.299g',0,'','Wędliny'],
['ćwiartka z kurczaka',4,'','Mięso'],
['Czosnek granulowany',0,'','Przyprawy'],
['Czekolada z s.migdał',0,'','Słodycze'],
['Czek.z orz.lask.',0,'','Słodycze'],
['Cwiartka z kurczaka',0,'','Mięso'],
['Cukier wanilinowy',3,'','Przyprawy'],
['Coca—cola nap.gaz.',2,'btn-success','Napoje'],
['Chust.hig.int.',0,'','Prod. przemysłowe'],
['Chrupki BBQ',0,'','Przekąski'],
['Chleb raz.na ma.św.',0,'','Art. mączne'],
['Chipsy ziem.pap.',0,'','Przekąski'],
['Chipsy Monst.Munch.',0,'','Przekąski'],
['Chipsy Cheetos',3,'','Przekąski'],
['Camembert 129g',0,'','Nabiał'],
['C.Minis Baton zboż.',0,'','Słodycze'],
['Bułka Kajzerka świeża ',0,'','Art. mączne'],
['BIO Ciastka owsiane',0,'','Słodycze'],
['Bella podpaski B.G.N',0,'','Prod. przemysłowe'],
['Baton zboż.Chocapic',1,'','Słodycze'],
['Banany Premium św.',0,'','Owoce'],
['Bagietka św.czosnk',0,'','Art. mączne'],
['Almette Serek',0,'','Nabiał'],
['Wino Alm. Alent.',11,'','Napoje'],
['Whisky',1,'','Napoje'],
['Ser topiony w plastrah',1,'btn-success','Nabiał'],
['Jabłka',6,'btn-success','Owoce'],
['Pomarańcze',4,'','Owoce'],
['Gruszki',0,'','Owoce'],
['Woreczki śniadaniowe',0,'','Prod. przemysłowe'],
['Wykałaczki',1,'btn-success','Prod. przemysłowe'],
['Kopytka',1,'btn-success','Mrożonki'],
['Masło w promocji',6,'btn-success','Nabiał']
];