var products = [
['Almette Serek',0,'','Nabiał'],
['Bagietka św.czosnk',0,'','Art. mączne'],
['Banany Premium św.',4,'btn-success','Owoce'],
['Baton zboż.Chocapic',1,'','Słodycze'],
['Bella podpaski B.G.N',0,'','Prod. przemysłowe'],
['BIO Ciastka owsiane',0,'','Słodycze'],
['Bułka Kajzerka świeża ',0,'','Art. mączne'],
['C.Minis Baton zboż.',0,'','Słodycze'],
['Camembert 129g',0,'','Nabiał'],
['Cheetosy pizza zielone',2,'btn-success','Przekąski'],
['Chipsy Cheetos',3,'','Przekąski'],
['Chipsy Monst.Munch.',0,'','Przekąski'],
['Chipsy ziem.pap.',0,'','Przekąski'],
['Chleb biały',0,'','Art. mączne'],
['Chleb raz.na ma.św.',0,'','Art. mączne'],
['Chleb tostowy biały',1,'btn-success','Art. mączne'],
['Chrupki BBQ',0,'','Przekąski'],
['Chusteczki hig. intymnej CIEN',1,'btn-success','Prod. przemysłowe'],
['Chusteczki higieniczne 90/100',2,'btn-success','Prod. przemysłowe'],
['Coca—cola nap.gaz.',2,'','Napoje'],
['Cukier wanilinowy',3,'','Przyprawy'],
['Cytryny',3,'btn-success','Owoce'],
['Czek.z orz.lask.',0,'','Słodycze'],
['Czekolada z s.migdał',0,'','Słodycze'],
['Czosnek granulowany',0,'','Przyprawy'],
['Ćwiartka z kurczaka',4,'','Mięso'],
['D.Szynka got.299g',0,'','Wędliny'],
['Donut Milka św',3,'','Słodycze'],
['Fasola zielona świeża',0,'','Warzywa'],
['Favita Ser',0,'','Nabiał'],
['Folia spożywcza',0,'','Prod. przemysłowe'],
['Frytki mrożone 7x7',1,'','Mrożonki'],
['Granola M.Czek.—kok.',0,'','Słodycze'],
['Groszek kons.puszka',2,'btn-success','Słoiki/puszki'],
['Gruszki',2,'btn-success','Owoce'],
['Herbata Rooibos, Pu—erh',0,'','Napoje'],
['Herbata ziel.79g',0,'','Napoje'],
['Herbatniki Maltanki',0,'','Słodycze'],
['Jabłka',4,'btn-success','Owoce'],
['Jaja L',0,'','Nabiał'],
['Jog.nat.3% b.lakt.',3,'','Nabiał'],
['Kabanosy drob.Tar.',1,'btn-success','Wędliny'],
['Ketchup łagodny',0,'','Słoiki/puszki'],
['Kiełb. krak. sucha',2,'btn-success','Wędliny'],
['Kiełki sort.',1,'','Warzywa'],
['Kinder Bueno baton',0,'','Słodycze'],
['Koncentrat pom.',0,'','Słoiki/puszki'],
['Koperek św.',0,'','Warzywa'],
['Kopytka',1,'btn-success','Mrożonki'],
['Koreczki śledziowe',0,'','Przekąski'],
['Kukurydza konserw.',0,'','Słoiki/puszki'],
['Lipton Herb.mroż.',0,'','Napoje'],
['Lipton Ice Tea',2,'btn-success','Napoje'],
['Liście laurowe',0,'','Przyprawy'],
['Lody jogurt. 469ml',0,'','Słodycze'],
['Lody Sandwich',6,'btn-success','Słodycze'],
['Lody Twister',0,'','Słodycze'],
['Łosoś dziki 9,378',0,'','Przekąski'],
['Łosoś wędzony199g 2',0,'','Przekąski'],
['Majonez KANIA',1,'btn-success','Słoiki/puszki'],
['Makaron kokard.500g',0,'','Art. mączne'],
['Maseczki 2x6ml',0,'','Prod. przemysłowe'],
['Masło w promocji',6,'','Nabiał'],
['Masz.d.gol. Venus',0,'','Prod. przemysłowe'],
['Mąka tortowa459 1kg',0,'','Art. mączne'],
['Miesz chińska mroż.',0,'','Mrożonki'],
['Miesz. żur. i nerk.',0,'','Przekąski'],
['Mieszanka sałat',0,'','Warzywa'],
['Mięso miel.w.—woł.',0,'','Mięso'],
['Mięso mielone woł.Pr',0,'','Mięso'],
['Migdały łuskane',0,'','Przyprawy'],
['Mleczko wan.w czekol',0,'','Słodycze'],
['Mleko bez laktozy',0,'','Nabiał'],
['Nat.pietruszki św.',1,'','Warzywa'],
['Nekt.pomar.59%1,5L',0,'','Napoje'],
['Nutella kr.cz.359g',0,'','Słoiki/puszki'],
['Oetker Budyń',0,'','Przyprawy'],
['Ogórki ziel świeże',1,'','Warzywa'],
['Orzechy nerkow.XXL',0,'','Przekąski'],
['Paluszki serowe',0,'','Nabiał'],
['Paluszki słone',1,'','Przekąski'],
['Papr żółta św. luz',0,'','Warzywa'],
['Papryka c. świeża',0,'','Warzywa'],
['Parówki Berlinki',0,'','Wędliny'],
['Patyczki kosmetyczne',0,'','Prod. przemysłowe'],
['Pieczarki świeże',0,'','Warzywa'],
['Pierogi z kap./grzyb',1,'btn-success','Mrożonki'],
['Piwo Lech Free Lim.Mięta',1,'','Napoje'],
['Piwo Perlenb. 0,5L',4,'','Napoje'],
['Pizza Margherit399g',2,'btn-success','Mrożonki'],
['Płatki Corn Flakes',0,'','Przekąski'],
['Płatki kosmetyczne',0,'','Prod. przemysłowe'],
['Płyn do płukania jam.ust. DENTALUX',2,'btn-success','Prod. przemysłowe'],
['Pomarańcze',3,'btn-success','Owoce'],
['Pomidor kiśc świeży',1,'','Warzywa'],
['Pomidory w puszce',0,'','Słoiki/puszki'],
['Popcorn do mik.solony',1,'btn-success','Przekąski'],
['Przyprawa Majeranek',1,'','Przyprawy'],
['Pstrąg łososiowy wędzony',0,'','Przekąski'],
['Ptasie mleczko',1,'','Słodycze'],
['Pure Frankfurterki',0,'','Wędliny'],
['Ryż Basmati',0,'','Art. mączne'],
['Schab wieprzowy b/k',0,'','Mięso'],
['Ser Gouda',2,'btn-success','Nabiał'],
['Ser Mozzarella',0,'','Nabiał'],
['Ser topiony pl.200g',0,'','Nabiał'],
['Ser topiony w plastrah',2,'btn-success','Nabiał'],
['Ser w plastrach',0,'','Nabiał'],
['Serek wiej.bez lak.',0,'','Nabiał'],
['Skrzydła z kurczaka',0,'','Mięso'],
['Sokołów Kabanosy',0,'','Wędliny'],
['Szczypiorek św.',0,'','Warzywa'],
['Szynka got.delik.',0,'','Wędliny'],
['Szynka Szwar.kroj.',0,'','Wędliny'],
['Twaróg półtł. klin.',1,'','Nabiał'],
['Tymb.Nekt.eop29%',0,'','Napoje'],
['Wafle ryżowe',0,'','Słodycze'],
['Whisky',1,'btn-success','Napoje'],
['Wino Alm. Alent.',3,'btn-success','Napoje'],
['Wino Cardal',2,'','Napoje'],
['Wkładki hig.long',0,'','Prod. przemysłowe'],
['Woreczki śniadaniowe',0,'','Prod. przemysłowe'],
['Worki na śmieci 69L',0,'','Prod. przemysłowe'],
['Wrigleys Guma II',0,'','Słodycze'],
['Wykałaczki',1,'','Prod. przemysłowe'],
['Zapiekanka z mocarellą i pieczarkami',2,'btn-success','Mrożonki'],
['Ziemniaki 5kg, św',1,'','Warzywa'],
['Zmywacz do paznokci CIEN',1,'btn-success','Prod. przemysłowe'],
['Zupa błyskaw.',1,'','Przekąski'],
['Żurawina susz.',1,'','Przekąski']
];