var products = [
['Żurawina susz.',1,'','Kasi'],
['Zupa błyskaw.',1,'','Kasi'],
['Ziemniaki 5kg, św',1,'','Kasi'],
['Wrigleys Guma II',0,'','Kasi'],
['Worki na śmieci 69L',0,'','Kasi'],
['Wkładki hig.long',0,'','Kasi'],
['Wino Cardal',12,'btn-success','Kasi'],
['Wafle ryżowe',0,'','Kasi'],
['Tymb.Nekt.eop29%',0,'','Kasi'],
['Twaróg półtł. klin.',0,'','Kasi'],
['Szynka Szwar.kroj.',0,'','Kasi'],
['Szynka got.delik.',0,'','Kasi'],
['Szczypiorek św.',0,'','Kasi'],
['Sokołów Kabanosy',0,'','Kasi'],
['Skrzydła z kurczaka',0,'','Kasi'],
['Serek wiej.bez lak.',0,'','Kasi'],
['Ser w plastrach',0,'','Kasi'],
['Ser topiony pl.200g',0,'','Kasi'],
['Ser Mozzarella',0,'','Kasi'],
['Ser Gouda',0,'','Kasi'],
['Schab wieprzowy b/k',0,'','Kasi'],
['Ryż Basmati',0,'','Kasi'],
['Pure Frankfurterki',0,'','Kasi'],
['Ptasie mleczko',0,'','Kasi'],
['Pstr.łososiow.wędz.',0,'','Kasi'],
['Przyprawa Majeranek',0,'','Kasi'],
['Popcorn do mik.sol.',0,'','Kasi'],
['pomidory w puszce',0,'','Kasi'],
['Pomidor kiśc świeży',0,'','Kasi'],
['Płatki kosmetyczne',0,'','Kasi'],
['Płatki Corn Flakes',0,'','Kasi'],
['Pizza Margherit399g',0,'','Kasi'],
['Piwo Perlenb. 0,5L',0,'','Kasi'],
['Pierogi z kap./grzyb',0,'','Kasi'],
['Pieczarki świeże',0,'','Kasi'],
['Patyczki kosmetyczne',0,'','Kasi'],
['Parówki Berlinki',0,'','Kasi'],
['Papryka c. świeża',0,'','Kasi'],
['Papr żółta św. luz',0,'','Kasi'],
['Paluszki słone',0,'','Kasi'],
['Paluszki serowe',0,'','Kasi'],
['Orzechy nerkow.XXL',0,'','Kasi'],
['Ogórki ziel świeże',0,'','Kasi'],
['Oetker Budyń',0,'','Kasi'],
['Nutella kr.cz.359g',0,'','Kasi'],
['Nekt.pomar.59%1,5L',0,'','Kasi'],
['Nat.pietruszki św.',0,'','Kasi'],
['Mleko bez laktozy',0,'','Kasi'],
['Mleczko wan.w czekol',0,'','Kasi'],
['Migdały łuskane',0,'','Kasi'],
['Mięso mielone woł.Pr',0,'','Kasi'],
['Mięso miel.w.—woł.',0,'','Kasi'],
['Mieszanka sałat',0,'','Kasi'],
['Miesz. żur. i nerk.',0,'','Kasi'],
['Miesz chińska mroż.',0,'','Kasi'],
['Mąka tortowa459 1kg',0,'','Kasi'],
['Masz.d.gol. Venus',0,'','Kasi'],
['Maseczki 2x6ml',0,'','Kasi'],
['Makaron kokard.500g',0,'','Kasi'],
['Łosoś wędzony199g 2',0,'','Kasi'],
['Łosoś dziki 9,378',0,'','Kasi'],
['Lody Twister',0,'','Kasi'],
['Lody Sandwich',0,'','Kasi'],
['Lody jogurt. 469ml',0,'','Kasi'],
['Liście laurowe',0,'','Kasi'],
['Lipton Ice Tea',0,'','Kasi'],
['Lipton Herb.mroż.',0,'','Kasi'],
['Lech Fr. Lim.Mięta',0,'','Kasi'],
['Kukurydza konserw.',0,'','Kasi'],
['Kor. śledziowe',0,'','Kasi'],
['Kopytka',0,'','Kasi'],
['Koperek św.',0,'','Kasi'],
['Koncentrat pom.',0,'','Kasi'],
['Kinder Bueno baton',0,'','Kasi'],
['Kiełki sort.',0,'','Kasi'],
['Kiełb. krak. sucha',0,'','Kasi'],
['Ketchup łagodny',0,'','Kasi'],
['Kania Majonez',0,'','Kasi'],
['Kabanosy drob.Tar.',0,'','Kasi'],
['Jog.nat.3% b.lakt.',0,'','Kasi'],
['Jaja L',0,'','Kasi'],
['Herbatniki Maltanki',0,'','Kasi'],
['Herbata ziel.79g',0,'','Kasi'],
['herb.Rooibos,Pu—erh',0,'','Kasi'],
['Groszek kons.puszka',0,'','Kasi'],
['Granola M.Czek.—kok.',0,'','Kasi'],
['Frytki mrożone 7x7',0,'','Kasi'],
['Folia spożywcza',0,'','Kasi'],
['Favita Ser',0,'','Kasi'],
['Fasola ziel świeża',0,'','Kasi'],
['Donut Milka św',3,'','Kasi'],
['D.Szynka got.299g',0,'','Kasi'],
['ćwiartka z kurczaka',4,'','Kasi'],
['Czosnek granulow.',0,'','Kasi'],
['Czekolada z s.migdał',0,'','Kasi'],
['Czek.z orz.lask.',0,'','Kasi'],
['Cwiartka z kurczaka',0,'','Kasi'],
['Cukier wanilinowy',3,'','Kasi'],
['Coca—cola nap.gaz.',0,'','Kasi'],
['Chust.hig.int.',0,'','Kasi'],
['Chrupki BBQ',0,'','Kasi'],
['Chleb raz.na ma.św.',0,'','Kasi'],
['Chipsy ziem.pap.',0,'','Kasi'],
['Chipsy Monst.Munch.',0,'','Kasi'],
['Chipsy Cheetos',3,'','Kasi'],
['Camembert 129g',0,'','Kasi'],
['C.Minis Baton zboż.',0,'','Kasi'],
['Bułka K. św.',0,'','Kasi'],
['BIO Ciastka owsiane',0,'','Kasi'],
['Bella podpaski B.G.N',0,'','Kasi'],
['Baton zboż.Chocapic',1,'','Kasi'],
['Banany Premium św.',0,'','Kasi'],
['Bagietka św.czosnk',3,'','Kasi'],
['Almette Serek',0,'','Kasi'],
['Alm. Alent. Wino',11,'btn-success','Kasi'],
['Whisky',2,'btn-success','Kasi']
];